#' Sample loss experience data
#'
#' @description
#' Calibrated synthetic long-format loss experience data for
#' demonstrating the lossratio package workflow. Generated
#' deterministically from `data-raw/make_experience.R` (set.seed =
#' 20260501). The marginal LR-by-development curve for each of the four
#' coverages is calibrated to the broad shape of a real long-term
#' insurance portfolio's first ten months of development; the elap_m
#' 11-30 plateau, all cohort-level patterns, demographic mixes, and
#' cell-level loss / rp values are randomly drawn. The SUR coverage
#' carries a synthetic 2024-04 cohort regime break (LR halved) so the
#' `detect_regime()` example has a clear shift to find.
#'
#' @format A `data.table` with 33,480 rows and 17 columns:
#' \describe{
#'   \item{cy, cyh, cyq, cym}{Calendar period (year / half / quarter / month) as `Date`.}
#'   \item{uy, uyh, uyq, uym}{Underwriting period (year / half / quarter / month) as `Date`.}
#'   \item{elap_y, elap_h, elap_q, elap_m}{Elapsed period (year / half / quarter / month) as integer.}
#'   \item{cv_nm}{Coverage name (character).}
#'   \item{age_band}{Age band (ordered factor).}
#'   \item{gender}{Gender (factor).}
#'   \item{loss}{Loss amount (perturbed).}
#'   \item{rp}{Risk premium amount (perturbed).}
#' }
#'
#' @source Generated by `data-raw/make_experience.R`. Per-coverage
#'   marginal LR-by-development calibrated to broad real-portfolio
#'   aggregates; cell-level structure and other patterns are random.
#'
#' @examples
#' \dontrun{
#' data(experience)
#' head(experience)
#'
#' exp <- as_experience(experience)
#' tri <- build_triangle(exp, group_var = cv_nm)
#' }
"experience"
